BASE_CURRENCIES = [
    "Exalted Orb",
    "Divine Orb",
    "Chaos Orb",
    "Regal Orb",
    "Orb of Alchemy",
    "Orb of Chance",
    "Vaal Orb",
    "Mirror of Kalandra",
    "Perfect Chaos Orb",
    "Perfect Exalted Orb",
    "Perfect Regal Orb",
    "Perfect Transmutation Orb",
    "Perfect Augmentation Orb",
    "Greater Chaos Orb",
    "Greater Exalted Orb",
    "Greater Regal Orb",
    "Greater Transmutation Orb",
    "Greater Augmentation Orb",
    "Orb of Transmutation",
    "Orb of Augmentation",
    "Artificer's Orb",
    "Lesser Jeweller's Orb",
    "Jeweller's Orb",
    "Greater Jeweller's Orb",
    "Perfect Jeweller's Orb",
    "Gemcutter's Prism",
    "Armourer's Scrap",
    "Blacksmith's Whetstone",
    "Glassblower's Bauble",
    "Scroll of Wisdom",
]
